language: node_js
node_js:
- '10'
- '12'
- lts/*
deploy:
  provider: npm
  email: vowstar@gmail.com
  api_key:
    secure: Z836FIkO23xafMt9hQZRQyftHKUIpO/CQaQzEc10hZTHWFHTf0uXJ4WESRPtlJaY9kXeRVPXFkLgARsVTz+ZzrAm4O7deyCc583CCLWGP4VFmUE8L/BVUjQzIVebrwwxL/FrU1NABQNW7ySbEbks8c22u057M8czeIuByRLTdpEcL7d1x7OqVHuWyOZukAgK6UST2Dg/vmFZd4vVBtlmoRFM3CWlv2mpU/zaSLBPHocKiowH2m/xzyn1df2FnNpGBX8oInkVXrDT2Smomk1xJgpY+mheqreNDDjhjb5gIfXOtlJPHuTYuKavRDLvaPJtVv246uMF0s8ING4f9cXhdAiI39vwLsltcXpn6C3cjlCPgncjVEeLMzT26H7ydawjiDXavwj/3yE/OEcrAz+PB/W5rK5Vr11eF2R1mLyKihTHI8Dj3Ux7gIEUmWTaaSQA4eytjNNJqIN/yh+UOOLZPvj5Y3DhH/i577lYPrIJPLp/mf/8y1Kdu99h7lkfQB6ECpCRPBbOF0sQjOlown8nfcnVqy5Mw+eceQMWeHbOZVq97N8+pp6EEfwJw1ZT8q0R6m/ODPmMCJsyz1E1wG81reIbbjg1WBfNQuaCpKdMhRQHxKYRXxuGj3Rxv4ezi2GDLP7ZXeG9rXXBLfnK8rrYbGnfhxjp1M5yEe8FIWmVg/c=
  on:
    tags: true
    repo: vowstar/node-plantuml
  skip_cleanup: true
