language: node_js
node_js:
  - "10"
  - "12"
  - "lts/*"
deploy:
  provider: npm
  email: vowstar@gmail.com
  api_key:
    secure: RS9vmrAlPtjsjZhH4Qi9uC8s4OyB+HcQDggMpNClyd9s4ARcVBlmqH5ZtB1OEByzwO5a0JVwDxFCme5XzIZeRK3fQIJKb680lL8ZJDeLntw5LVTXVP54bZJJmyzyxiXWpG+3GzrnNtCdXcI6cyykfwnxpDYT636cgAVW5CPpkSVAocjDQUXZFRdR2qJ9fQvDZGxyvOQvb3GAv/ttsgUyG953f0Oifymk9cUd6K7Vw4LSsX364TGS4PNIoCt4oLL03xqno/bfjslIRPl5mXRcL9yGYMugOV0+vNpfcnemUUweD/3TJfiB78admFa6ZdDLn0BIt1waOaRtpXnbOZMJMvokRpEgGUk7I/YJTijAnGjTz4ERjhXTMEVi/kWsngLpnjKoE8Z1G64rzILvXzekGuNGe40sYIHalUh6x4DMFCMkwPW3ml3tChSDzm9lSZmtiOrBWHMC6cYe5eSXWX+xrhtJMKKuUGrfIXykbZqq0IapCd9feHpN8UrUp+x8LkZBWfpMiLGV1KDx2z0ixQm/1hz7Wfy7xRt7CFkhJV/K12dFjxhMndfApIuOIhMhbO3XP+nEWVuHlnBCLArI1c7sBPliijwCoAdkpQvE3xex7P3DbEVdq5rdMX7zERkamZYyGArkT82Unqgr0ULDc/PkhWt/rbhKQoXsNQUlvc4qnIo=
  on:
    tags: true
    repo: vowstar/node-plantuml
  skip_cleanup: true
