language: node_js
node_js:
- '10'
- '12'
- lts/*
deploy:
  provider: npm
  email: vowstar@gmail.com
  api_key:
    secure: CXFzHuE3GmUY/a6DmKbaU3DuqIK/0FvHXltAw6xjbn9BcxEzlJpPyhikkb/8ElHlRW6a+CEbkZMQrCeaU00ioTTziMkZ+It1NSSvyusKDlsxKI2tKIsUKdBRKPnukwHsCo0uqyPNyw7ole/byUYi2dZeaNKvpUpmj1eFB2wOf4bTkaYAE39eTlZ0Nta+7r+cBUd9N03tsIJzHa7RatbtDMZ6x8mcaBE88er47WR4NTDqc9hyp4/PR7ZQdULxqAZuUS+giGBoqdf0hBTuy75QCiBUCFbBkK1r/7VyTLupwRr8cMYDydhObKdH6NVaquJsFvSuEdvYjg9kJz4Pa3dlv+PGDmTN2XThP/aHaKfB1ihU87U47XCMGFZbCedzgRp3Muh3jYaUjJqAX9rw/c3DHQXpvVmF2RghXoucJxvjJaAcPtwBKNW63W7RMutSjz11QFM55KyPSLSEa00agdsfpu/CUXjKZHnAZt1brlfjJKUOo6LvDKZ/T3gNFhCCsOGgf4vM2crStgyMiJTwNy5L6QiDxuoQVK9Hx2VgOu0IpLiLoPWvAdlD7y4rRet9/u2SS8CLQEg3XQOc/t5eSHnKp30rGLQiElkjcXRkH1wIcJT62aA5vcWcOyINhAU2aVSyp8UzGNjEzcR04NCzKRV1s2Zh6WqH+BzY93xbPfXCSPY=
  on:
    tags: true
    repo: vowstar/node-plantuml
  skip_cleanup: true
